ID2NAME = {
     0: "Rest",

     # Exercise A (blue column, 1 – 12)
     1: "Index flexion",
     2: "Index extension",
     3: "Middle flexion",
     4: "Middle extension",
     5: "Ring flexion",
     6: "Ring extension",
     7: "Little finger flexion",
     8: "Little finger extension",
     9: "Thumb adduction",
    10: "Thumb abduction",
    11: "Thumb flexion",
    12: "Thumb extension",

     # Exercise B (pink column, 13 – 29)
    13: "Thumb up",
    14: "Extension of index and middle, flexion of the others",
    15: "Flexion of ring and little finger, extension of the others",
    16: "Thumb opposing base of little finger",
    17: "Abduction of all fingers",
    18: "Fingers flexed together in fist",
    19: "Pointing index",
    20: "Adduction of extended fingers",
    21: "Wrist supination (axis: middle finger)",
    22: "Wrist pronation (axis: middle finger)",
    23: "Wrist supination (axis: little finger)",
    24: "Wrist pronation (axis: little finger)",
    25: "Wrist flexion",
    26: "Wrist extension",
    27: "Wrist radial deviation",
    28: "Wrist ulnar deviation",
    29: "Wrist extension with closed hand",

     # Exercise C (green column, 30 – 52)
    30: "Large diameter grasp",
    31: "Small diameter grasp (power grip)",
    32: "Fixed hook grasp",
    33: "Index finger extension grasp",
    34: "Medium wrap",
    35: "Ring grasp",
    36: "Prismatic four fingers grasp",
    37: "Stick grasp",
    38: "Writing tripod grasp",
    39: "Power sphere grasp",
    40: "Three finger sphere grasp",
    41: "Precision sphere grasp",
    42: "Tripod grasp",
    43: "Prismatic pinch grasp",
    44: "Tip pinch grasp",
    45: "Quadpod grasp",
    46: "Lateral grasp",
    47: "Parallel extension grasp",
    48: "Extension type grasp",
    49: "Power disk grasp",
    50: "Open a bottle with a tripod grasp",
    51: "Turn a screw (grasp the screwdriver with a stick grasp)",
    52: "Cut something (grasp the knife with an index finger extension grasp)",
}

# reverse lookup
NAME2ID = {v: k for k, v in ID2NAME.items()}
